//! macOS bundles generated by the CLI.
//!
//! The Jcode Desktop app (`/Applications/Jcode.app`,
//! `dev.solosystems.jcode.desktop`) is the only user-facing Jcode launcher on
//! macOS. Older CLI releases also generated a Terminal launcher bundle in
//! `~/Applications` and published the notification broker there, so users saw
//! up to three "Jcode" entries in Spotlight and Launchpad, two with the old
//! icon. The CLI now installs only the faceless notification broker, in a
//! hidden directory which Spotlight and Launchpad do not index, and removes the
//! legacy bundles it created. Bundles are identified by their bundle identifier
//! so a Desktop app the user placed in `~/Applications` is never touched.

use super::SetupHintsState;
use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

const MACOS_APP_ICON_FILE_NAME: &str = "Jcode.icns";
const MACOS_APP_ICON_BYTES: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../assets/app-icons/Jcode.icns"
));
const MACOS_NOTIFICATION_APP_NAME: &str = "Jcode Notifications.app";
const MACOS_NOTIFICATION_EXECUTABLE: &str = "jcode-notification-broker";
const MACOS_NOTIFICATION_VERSION_MARKER: &str = "jcode-broker-version";
const MACOS_NOTIFICATION_BUNDLE_ID: &str = "com.jcode.notifications";

/// Bundle identifiers of CLI-generated launchers that must be removed.
/// `com.jcode.app` is the original `jcode.app`, `com.jcode.launcher` the later
/// `Jcode.app` Terminal launcher.
const LEGACY_LAUNCHER_BUNDLE_IDS: &[&str] = &["com.jcode.app", "com.jcode.launcher"];

pub(super) fn should_refresh_macos_app_launcher(state: &SetupHintsState) -> bool {
    let (Ok(broker_dir), Ok(applications)) =
        (macos_notification_broker_dir(), user_applications_dir())
    else {
        return !state.desktop_shortcut_created;
    };
    !state.desktop_shortcut_created
        || !macos_notification_broker_is_valid(&broker_dir)
        || !legacy_macos_bundles(&applications).is_empty()
}

/// Install the notification broker and remove legacy CLI-generated bundles.
/// Returns the broker bundle path.
pub(super) fn install_macos_app_launcher() -> Result<PathBuf> {
    remove_legacy_macos_bundles()?;
    let exe = std::env::current_exe()?;
    install_macos_notification_broker(&exe)
}

/// Remove every legacy CLI-generated bundle from `~/Applications`.
/// Returns the removed paths.
pub(super) fn remove_legacy_macos_bundles() -> Result<Vec<PathBuf>> {
    let applications = user_applications_dir()?;
    let legacy = legacy_macos_bundles(&applications);
    for path in &legacy {
        unregister_macos_bundle(path);
        remove_path_if_exists(path)?;
    }
    Ok(legacy)
}

fn user_applications_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("Could not find home directory")?;
    Ok(home.join("Applications"))
}

/// Hidden, home-anchored location for the broker. Dot-directories are skipped
/// by Spotlight and Launchpad, yet LaunchServices can still open the bundle by
/// path. It sits beside the durable inbox the broker drains.
pub(super) fn macos_notification_broker_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("Could not find home directory")?;
    Ok(macos_notification_broker_dir_in(&home))
}

fn macos_notification_broker_dir_in(home: &Path) -> PathBuf {
    home.join(".jcode")
        .join("notifications")
        .join("macos")
        .join(MACOS_NOTIFICATION_APP_NAME)
}

/// Legacy bundles in `applications`: CLI-generated launchers (any letter case
/// of `jcode.app`) and the broker's former location. Bundles are matched on
/// their exact directory entry name, which matters on case-insensitive
/// volumes, and on their bundle identifier.
fn legacy_macos_bundles(applications: &Path) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(applications) else {
        return Vec::new();
    };
    let mut legacy = Vec::new();
    for entry in entries.filter_map(|entry| entry.ok()) {
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        let path = entry.path();
        let wanted: &[&str] = if name.eq_ignore_ascii_case("jcode.app") {
            LEGACY_LAUNCHER_BUNDLE_IDS
        } else if name == MACOS_NOTIFICATION_APP_NAME {
            &[MACOS_NOTIFICATION_BUNDLE_ID]
        } else {
            continue;
        };
        if bundle_identifier(&path).is_some_and(|id| wanted.contains(&id.as_str())) {
            legacy.push(path);
        }
    }
    legacy.sort();
    legacy
}

/// Read `CFBundleIdentifier` from a bundle's XML Info.plist. The CLI always
/// wrote XML plists, so no binary-plist parser is needed. Anything else,
/// including a binary plist from a signed Desktop app, yields its identifier
/// only if present as XML, otherwise `None` and the bundle is left alone.
fn bundle_identifier(app_dir: &Path) -> Option<String> {
    let plist = std::fs::read_to_string(app_dir.join("Contents").join("Info.plist")).ok()?;
    let key = plist.find("<key>CFBundleIdentifier</key>")?;
    let rest = &plist[key..];
    let start = rest.find("<string>")? + "<string>".len();
    let end = rest[start..].find("</string>")?;
    Some(rest[start..start + end].trim().to_string())
}

fn macos_notification_broker_executable_path(app_dir: &Path) -> PathBuf {
    app_dir
        .join("Contents")
        .join("MacOS")
        .join(MACOS_NOTIFICATION_EXECUTABLE)
}

fn macos_notification_broker_marker_path(app_dir: &Path) -> PathBuf {
    app_dir
        .join("Contents")
        .join("Resources")
        .join(MACOS_NOTIFICATION_VERSION_MARKER)
}

fn macos_notification_broker_icon_path(app_dir: &Path) -> PathBuf {
    app_dir
        .join("Contents")
        .join("Resources")
        .join(MACOS_APP_ICON_FILE_NAME)
}

fn macos_notification_broker_is_valid(app_dir: &Path) -> bool {
    app_dir.is_dir()
        && app_dir.join("Contents").join("Info.plist").is_file()
        && macos_notification_broker_executable_path(app_dir).is_file()
        && macos_notification_broker_icon_path(app_dir).is_file()
        && std::fs::read_to_string(macos_notification_broker_marker_path(app_dir))
            .is_ok_and(|version| version.trim() == jcode_build_meta::version())
}

/// Install a faceless Notification Center owner using the already-built jcode
/// executable as a multicall binary. Hard-linking keeps the generated helper
/// tiny and architecture-correct for both Intel and Apple Silicon artifacts;
/// copying is the reliable fallback when the home directory spans volumes.
fn install_macos_notification_broker(jcode_executable: &Path) -> Result<PathBuf> {
    let app_dir = macos_notification_broker_dir()?;
    let parent = app_dir
        .parent()
        .context("notification broker bundle has no parent")?;
    std::fs::create_dir_all(parent)?;

    let staging = parent.join(format!(
        ".Jcode Notifications.app.installing-{}",
        std::process::id()
    ));
    remove_path_if_exists(&staging)?;
    let contents = staging.join("Contents");
    let macos = contents.join("MacOS");
    let resources = contents.join("Resources");
    std::fs::create_dir_all(&macos)?;
    std::fs::create_dir_all(&resources)?;

    let broker_executable = macos.join(MACOS_NOTIFICATION_EXECUTABLE);
    if std::fs::hard_link(jcode_executable, &broker_executable).is_err() {
        std::fs::copy(jcode_executable, &broker_executable).with_context(|| {
            format!(
                "failed to install notification broker executable from {}",
                jcode_executable.display()
            )
        })?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&broker_executable, std::fs::Permissions::from_mode(0o755))?;
    }
    std::fs::write(
        resources.join(MACOS_APP_ICON_FILE_NAME),
        MACOS_APP_ICON_BYTES,
    )?;
    std::fs::write(
        resources.join(MACOS_NOTIFICATION_VERSION_MARKER),
        format!("{}\n", jcode_build_meta::version()),
    )?;
    std::fs::write(contents.join("Info.plist"), macos_notification_info_plist())?;

    if !macos_notification_broker_is_valid(&staging) {
        remove_path_if_exists(&staging)?;
        anyhow::bail!(
            "notification broker bundle is incomplete after setup: {}",
            staging.display()
        );
    }

    remove_path_if_exists(&app_dir)?;
    std::fs::rename(&staging, &app_dir).with_context(|| {
        format!(
            "failed to publish notification broker bundle at {}",
            app_dir.display()
        )
    })?;
    register_macos_bundle(&app_dir);
    Ok(app_dir)
}

fn macos_notification_info_plist() -> String {
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Jcode Notifications</string>
    <key>CFBundleDisplayName</key>
    <string>Jcode Notifications</string>
    <key>CFBundleIdentifier</key>
    <string>{bundle_id}</string>
    <key>CFBundleVersion</key>
    <string>{version}</string>
    <key>CFBundleShortVersionString</key>
    <string>{version}</string>
    <key>CFBundleExecutable</key>
    <string>{executable}</string>
    <key>CFBundleIconFile</key>
    <string>{icon}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <true/>
    <key>LSMultipleInstancesProhibited</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
"#,
        version = jcode_build_meta::version(),
        executable = MACOS_NOTIFICATION_EXECUTABLE,
        icon = MACOS_APP_ICON_FILE_NAME,
        bundle_id = MACOS_NOTIFICATION_BUNDLE_ID,
    )
}

fn remove_path_if_exists(path: &Path) -> Result<()> {
    if !path.exists() {
        return Ok(());
    }

    let metadata = std::fs::symlink_metadata(path)
        .with_context(|| format!("failed to inspect existing path {}", path.display()))?;
    if metadata.file_type().is_dir() {
        std::fs::remove_dir_all(path)
            .with_context(|| format!("failed to remove directory {}", path.display()))?;
    } else {
        std::fs::remove_file(path)
            .with_context(|| format!("failed to remove file {}", path.display()))?;
    }
    Ok(())
}

fn lsregister_path() -> Option<&'static Path> {
    let path = Path::new(
        "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister",
    );
    path.exists().then_some(path)
}

/// Register the broker with LaunchServices so `open -gj` resolves it and its
/// bundle identifier owns Notification Center permission. It is deliberately
/// not passed to `mdimport`: it is a faceless helper, not a launchable app.
fn register_macos_bundle(app_dir: &Path) {
    if let Some(lsregister) = lsregister_path() {
        let _ = std::process::Command::new(lsregister)
            .args(["-f", app_dir.to_string_lossy().as_ref()])
            .status();
    }
}

/// Drop a bundle from LaunchServices before deleting it, so Launchpad and
/// Spotlight forget the icon immediately instead of showing a dead entry.
fn unregister_macos_bundle(app_dir: &Path) {
    if let Some(lsregister) = lsregister_path() {
        let _ = std::process::Command::new(lsregister)
            .args(["-u", app_dir.to_string_lossy().as_ref()])
            .status();
    }
}

#[cfg(test)]
#[path = "macos_launcher_tests.rs"]
mod macos_launcher_tests;
