use super::*;
use jcode_update_core::parse_sha256sums;
use sha2::{Digest, Sha256};

#[test]
fn test_version_is_newer() {
    assert!(version_is_newer("0.1.3", "0.1.2"));
    assert!(version_is_newer("0.2.0", "0.1.9"));
    assert!(version_is_newer("1.0.0", "0.9.9"));
    assert!(!version_is_newer("0.1.2", "0.1.2"));
    assert!(!version_is_newer("0.1.1", "0.1.2"));
    assert!(!version_is_newer("0.0.9", "0.1.0"));
}

#[test]
fn test_asset_name() {
    let name = get_asset_name();
    assert!(name.starts_with("jcode-"));
}

#[test]
fn test_format_download_progress_bar_known_total() {
    let rendered = format_download_progress_bar(DownloadProgress {
        downloaded: 512,
        total: Some(1024),
    });
    assert!(rendered.contains("50%"));
    assert!(rendered.contains("512 B/1.0 KiB"));
    assert!(rendered.contains('█'));
    assert!(rendered.contains('░'));
}

#[test]
fn test_format_download_progress_bar_unknown_total() {
    let rendered = format_download_progress_bar(DownloadProgress {
        downloaded: 2 * 1024 * 1024,
        total: None,
    });
    assert_eq!(rendered, "Downloading update... 2.0 MiB downloaded");
}

#[test]
fn test_parse_sha256sums_accepts_standard_and_binary_lines() {
    let digest_a = "a".repeat(64);
    let digest_b = "B".repeat(64);
    let digest_b_lower = "b".repeat(64);
    let contents = format!(
        "# generated by release workflow\n{}  jcode-linux-x86_64.tar.gz\r\n{} *jcode-windows-x86_64.exe\n",
        digest_a, digest_b
    );
    let parsed = parse_sha256sums(&contents).unwrap();
    assert_eq!(
        parsed.get("jcode-linux-x86_64.tar.gz").map(String::as_str),
        Some(digest_a.as_str())
    );
    assert_eq!(
        parsed.get("jcode-windows-x86_64.exe").map(String::as_str),
        Some(digest_b_lower.as_str())
    );
}

#[test]
fn test_verify_asset_checksum_text_accepts_matching_digest() {
    let bytes = b"hello update";
    let digest = format!("{:x}", Sha256::digest(bytes));
    let contents = format!("{}  jcode-linux-x86_64.tar.gz\n", digest);
    verify_asset_checksum_text(&contents, "jcode-linux-x86_64.tar.gz", bytes).unwrap();
}

#[test]
fn test_verify_asset_checksum_text_rejects_mismatch() {
    let wrong = "0".repeat(64);
    let contents = format!("{}  jcode-linux-x86_64.tar.gz\n", wrong);
    let err = verify_asset_checksum_text(&contents, "jcode-linux-x86_64.tar.gz", b"actual")
        .unwrap_err()
        .to_string();
    assert!(err.contains("Checksum mismatch"));
}

#[test]
fn test_verify_asset_checksum_text_requires_asset_entry() {
    let digest = "1".repeat(64);
    let contents = format!("{}  other-asset.tar.gz\n", digest);
    let err = verify_asset_checksum_text(&contents, "jcode-linux-x86_64.tar.gz", b"actual")
        .unwrap_err()
        .to_string();
    assert!(err.contains("does not list"));
}

#[test]
fn test_parse_sha256sums_rejects_invalid_digest() {
    let err = parse_sha256sums("not-a-sha  jcode-linux-x86_64.tar.gz\n")
        .unwrap_err()
        .to_string();
    assert!(err.contains("invalid SHA256 digest"));
}

#[test]
fn release_update_rejects_equal_or_older_versions_without_ancestry_probe() {
    for release_build in [true, false] {
        for release in ["v0.82.9", "v0.83.0"] {
            assert!(
                !release_is_update_with(release, "0.83.0", release_build, || {
                    panic!("older releases must not need a GitHub ancestry check")
                })
                .unwrap()
            );
        }
    }
}

#[test]
fn release_update_allows_newer_release_build_without_ancestry_probe() {
    assert!(
        release_is_update_with("v0.83.1", "0.83.0", true, || {
            panic!("release builds must not need a GitHub ancestry check")
        })
        .unwrap()
    );
}

#[test]
fn release_update_preserves_dev_commits_even_when_release_number_is_newer() {
    assert!(!release_is_update_with("v0.84.0", "0.83.0", false, || Ok(false)).unwrap());
}

#[test]
fn release_update_allows_dev_build_behind_release() {
    assert!(release_is_update_with("v0.83.1", "0.83.0", false, || Ok(true)).unwrap());
}

#[test]
fn release_update_fails_closed_when_dev_ancestry_cannot_be_verified() {
    let result = release_is_update_with("v0.84.0", "0.83.0", false, || {
        anyhow::bail!("Cannot verify development build ancestry")
    });
    assert!(result.unwrap_err().to_string().contains("Cannot verify"));
}

#[test]
fn test_is_release_build() {
    assert!(!is_release_build());
}

#[test]
fn test_should_auto_update_dev_build() {
    assert!(!should_auto_update());
}

#[test]
fn git_managed_auto_update_skip_logs_actionable_explanation() {
    let temp = tempfile::tempdir().expect("temporary directory");
    let managed_root = temp.path().join("managed");
    let bin_dir = managed_root.join("bin");
    std::fs::create_dir_all(managed_root.join(".git")).expect("create git marker");
    std::fs::create_dir_all(&bin_dir).expect("create bin directory");

    let executable = bin_dir.join("jcode");
    let mut logged = Vec::new();
    assert!(!should_auto_update_with(
        false,
        true,
        || Some(executable),
        |message| logged.push(message.to_owned()),
    ));
    assert_eq!(logged.len(), 1, "the skip reason should be logged once");
    assert!(logged[0].contains("Automatic update check skipped"));
    assert!(logged[0].contains("Rebuild this checkout executable"));
    assert!(logged[0].contains("run `jcode update` and relaunch with the installed"));

    let standalone = temp.path().join("standalone/jcode");
    let mut unexpected_logs = Vec::new();
    assert!(should_auto_update_with(
        false,
        true,
        || Some(standalone),
        |message| unexpected_logs.push(message.to_owned()),
    ));
    assert!(unexpected_logs.is_empty());
}

#[test]
fn test_summarize_git_pull_failure_diverged() {
    let stderr = b"hint: You have divergent branches and need to specify how to reconcile them.\nfatal: Need to specify how to reconcile divergent branches.\n";
    assert_eq!(
        summarize_git_pull_failure(stderr),
        jcode_update_core::GIT_PULL_DIVERGED_SUMMARY
    );
    assert!(jcode_update_core::summary_is_divergence(
        &summarize_git_pull_failure(stderr)
    ));
}

#[test]
fn test_summarize_git_pull_failure_no_tracking_branch() {
    let stderr = b"There is no tracking information for the current branch.\n";
    assert_eq!(
        summarize_git_pull_failure(stderr),
        "git pull failed: current branch has no upstream tracking branch"
    );
}

#[test]
fn test_summarize_git_pull_failure_uses_first_non_hint_line() {
    let stderr = b"hint: test hint\nfatal: repository not found\n";
    assert_eq!(
        summarize_git_pull_failure(stderr),
        "git pull failed: repository not found"
    );
}

#[test]
fn test_estimate_release_update_duration_uses_size_buckets() {
    assert_eq!(
        estimate_release_update_duration(10 * 1024 * 1024, None),
        Duration::from_secs(10)
    );
    assert_eq!(
        estimate_release_update_duration(40 * 1024 * 1024, None),
        Duration::from_secs(35)
    );
}

#[test]
fn test_estimate_source_update_duration_prefers_history() {
    assert_eq!(
        estimate_source_update_duration(true, true, Some(123.4)),
        Duration::from_secs(123)
    );
}

#[test]
fn test_content_range_total_parses_total() {
    use reqwest::header::{HeaderMap, HeaderValue};
    // Build a Response is awkward; test the parser via a header map directly.
    let mut headers = HeaderMap::new();
    headers.insert(
        reqwest::header::CONTENT_RANGE,
        HeaderValue::from_static("bytes 200-1023/1024"),
    );
    let parsed = headers
        .get(reqwest::header::CONTENT_RANGE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.rsplit('/').next())
        .and_then(|total| total.trim().parse::<u64>().ok());
    assert_eq!(parsed, Some(1024));
}

#[test]
fn test_content_range_total_unknown_size_is_none() {
    use reqwest::header::{HeaderMap, HeaderValue};
    let mut headers = HeaderMap::new();
    headers.insert(
        reqwest::header::CONTENT_RANGE,
        HeaderValue::from_static("bytes 200-1023/*"),
    );
    let parsed = headers
        .get(reqwest::header::CONTENT_RANGE)
        .and_then(|value| value.to_str().ok())
        .and_then(|value| value.rsplit('/').next())
        .and_then(|total| total.trim().parse::<u64>().ok());
    assert_eq!(parsed, None);
}

/// End-to-end resume test: a tiny HTTP server serves the first half of the
/// body then drops the connection, and on the resumed Range request serves
/// the rest. The download must recover and return the full payload.
#[test]
fn test_download_asset_with_resume_recovers_from_dropped_connection() {
    use std::io::{BufRead, BufReader, Write};
    use std::net::TcpListener;
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    let payload: Vec<u8> = (0..2000u32).map(|i| (i % 251) as u8).collect();
    let total = payload.len();
    let split = total / 2;

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = listener.local_addr().expect("addr");
    let payload_for_server = payload.clone();
    let request_count = Arc::new(AtomicUsize::new(0));
    let request_count_server = Arc::clone(&request_count);

    let handle = std::thread::spawn(move || {
        // Serve exactly two connections: first truncated, second resumed.
        for _ in 0..2 {
            let Ok((mut stream, _)) = listener.accept() else {
                break;
            };
            let n = request_count_server.fetch_add(1, Ordering::SeqCst);

            // Parse request headers; look for a Range header.
            let mut range_start = 0usize;
            {
                let mut reader = BufReader::new(stream.try_clone().expect("clone"));
                let mut line = String::new();
                loop {
                    line.clear();
                    if reader.read_line(&mut line).unwrap_or(0) == 0 {
                        break;
                    }
                    let trimmed = line.trim_end();
                    if let Some(rest) = trimmed.to_ascii_lowercase().strip_prefix("range: bytes=")
                        && let Some(start) = rest.split('-').next()
                    {
                        range_start = start.trim().parse().unwrap_or(0);
                    }
                    if trimmed.is_empty() {
                        break;
                    }
                }
            }

            if n == 0 {
                // First attempt: 200 OK, but only send the first half, then
                // close mid-stream to simulate a stalled/dropped connection.
                let header = format!(
                    "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nAccept-Ranges: bytes\r\n\r\n",
                    total
                );
                let _ = stream.write_all(header.as_bytes());
                let _ = stream.write_all(&payload_for_server[..split]);
                let _ = stream.flush();
                // Drop connection without finishing the body.
            } else {
                // Resumed attempt: serve 206 with the remaining bytes.
                let remaining = &payload_for_server[range_start..];
                let header = format!(
                    "HTTP/1.1 206 Partial Content\r\nContent-Length: {}\r\nContent-Range: bytes {}-{}/{}\r\n\r\n",
                    remaining.len(),
                    range_start,
                    total - 1,
                    total
                );
                let _ = stream.write_all(header.as_bytes());
                let _ = stream.write_all(remaining);
                let _ = stream.flush();
            }
        }
    });

    let client = reqwest::blocking::Client::builder()
        .build()
        .expect("client");
    let url = format!("http://{}/asset", addr);
    let (bytes, parsed_total) =
        download_asset_with_resume(&client, &url, Some(total as u64), &mut |_| {})
            .expect("download should recover");

    handle.join().ok();

    assert_eq!(bytes, payload, "resumed download must reconstruct payload");
    assert_eq!(parsed_total, Some(total as u64));
    assert_eq!(
        request_count.load(Ordering::SeqCst),
        2,
        "should have made an initial + one resume request"
    );
}

/// A connection that keeps dropping but always advances a little must still
/// complete: forward progress resets the consecutive-stall budget, so the
/// number of resumes can exceed DOWNLOAD_MAX_ATTEMPTS as long as each one
/// delivers new bytes.
#[test]
fn test_download_asset_with_resume_tolerates_many_progressing_drops() {
    use std::io::{BufRead, BufReader, Write};
    use std::net::TcpListener;
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    let payload: Vec<u8> = (0..3000u32).map(|i| (i % 251) as u8).collect();
    let total = payload.len();
    // Each attempt delivers only this many bytes, then drops, so it takes
    // many more than DOWNLOAD_MAX_ATTEMPTS attempts to finish.
    let chunk = 100usize;

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = listener.local_addr().expect("addr");
    let payload_for_server = payload.clone();
    let request_count = Arc::new(AtomicUsize::new(0));
    let request_count_server = Arc::clone(&request_count);

    let handle = std::thread::spawn(move || {
        loop {
            let Ok((mut stream, _)) = listener.accept() else {
                break;
            };
            let n = request_count_server.fetch_add(1, Ordering::SeqCst);

            let mut range_start = 0usize;
            {
                let mut reader = BufReader::new(stream.try_clone().expect("clone"));
                let mut line = String::new();
                loop {
                    line.clear();
                    if reader.read_line(&mut line).unwrap_or(0) == 0 {
                        break;
                    }
                    let trimmed = line.trim_end();
                    if let Some(rest) = trimmed.to_ascii_lowercase().strip_prefix("range: bytes=")
                        && let Some(start) = rest.split('-').next()
                    {
                        range_start = start.trim().parse().unwrap_or(0);
                    }
                    if trimmed.is_empty() {
                        break;
                    }
                }
            }

            let end = (range_start + chunk).min(total);
            let body = &payload_for_server[range_start..end];
            let header = if n == 0 {
                format!(
                    "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nAccept-Ranges: bytes\r\n\r\n",
                    total
                )
            } else {
                format!(
                    "HTTP/1.1 206 Partial Content\r\nContent-Length: {}\r\nContent-Range: bytes {}-{}/{}\r\n\r\n",
                    total - range_start,
                    range_start,
                    total - 1,
                    total
                )
            };
            let _ = stream.write_all(header.as_bytes());
            let _ = stream.write_all(body);
            let _ = stream.flush();
            // Drop after a partial chunk unless we've reached the end.
            if end >= total {
                break;
            }
        }
    });

    let client = reqwest::blocking::Client::builder()
        .build()
        .expect("client");
    let url = format!("http://{}/asset", addr);
    let (bytes, _total) =
        download_asset_with_resume(&client, &url, Some(total as u64), &mut |_| {})
            .expect("progressing download should complete");

    handle.join().ok();

    assert_eq!(bytes, payload);
    assert!(
        request_count.load(Ordering::SeqCst) > DOWNLOAD_MAX_ATTEMPTS,
        "test should require more than the stall budget of resumes"
    );
}

/// Mirrors the real #293 shape closely: the caller has *no* size hint
/// (None), a slow connection drops repeatedly, and the size is learned from
/// the server (Content-Length on the initial 200, Content-Range on the 206
/// resumes, exactly like a GitHub release asset). The download must still
/// complete, learn the correct total, and report progress that never moves
/// backwards across reconnects (so the UI bar can't appear to regress).
#[test]
fn test_download_asset_with_resume_unknown_total_and_monotonic_progress() {
    use std::io::{BufRead, BufReader, Write};
    use std::net::TcpListener;
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    let payload: Vec<u8> = (0..5000u32).map(|i| (i % 251) as u8).collect();
    let total = payload.len();
    let chunk = 400usize;

    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = listener.local_addr().expect("addr");
    let payload_for_server = payload.clone();
    let request_count = Arc::new(AtomicUsize::new(0));
    let request_count_server = Arc::clone(&request_count);

    let handle = std::thread::spawn(move || {
        loop {
            let Ok((mut stream, _)) = listener.accept() else {
                break;
            };
            let n = request_count_server.fetch_add(1, Ordering::SeqCst);

            let mut range_start = 0usize;
            {
                let mut reader = BufReader::new(stream.try_clone().expect("clone"));
                let mut line = String::new();
                loop {
                    line.clear();
                    if reader.read_line(&mut line).unwrap_or(0) == 0 {
                        break;
                    }
                    let trimmed = line.trim_end();
                    if let Some(rest) = trimmed.to_ascii_lowercase().strip_prefix("range: bytes=")
                        && let Some(start) = rest.split('-').next()
                    {
                        range_start = start.trim().parse().unwrap_or(0);
                    }
                    if trimmed.is_empty() {
                        break;
                    }
                }
            }

            let end = (range_start + chunk).min(total);
            let body = &payload_for_server[range_start..end];
            // Like a real GitHub asset: the initial 200 carries the full
            // Content-Length (so a mid-stream drop is detectable), and the
            // 206 resumes carry Content-Range. The *caller* still gets no
            // size hint, so the total must be learned from these headers.
            let header = if n == 0 {
                format!(
                    "HTTP/1.1 200 OK\r\nContent-Length: {}\r\nAccept-Ranges: bytes\r\n\r\n",
                    total
                )
            } else {
                format!(
                    "HTTP/1.1 206 Partial Content\r\nContent-Length: {}\r\nContent-Range: bytes {}-{}/{}\r\n\r\n",
                    total - range_start,
                    range_start,
                    total - 1,
                    total
                )
            };
            let _ = stream.write_all(header.as_bytes());
            let _ = stream.write_all(body);
            let _ = stream.flush();
            // Drop after a partial chunk unless we've reached the end.
            if end >= total {
                break;
            }
        }
    });

    let client = reqwest::blocking::Client::builder()
        .build()
        .expect("client");
    let url = format!("http://{}/asset", addr);

    let mut progress_points: Vec<u64> = Vec::new();
    let mut seen_total: Option<u64> = None;
    let (bytes, parsed_total) = download_asset_with_resume(
        &client,
        &url,
        None, // no size hint, like a fresh download with no metadata
        &mut |p| {
            progress_points.push(p.downloaded);
            if p.total.is_some() {
                seen_total = p.total;
            }
        },
    )
    .expect("download with unknown caller hint should complete");

    handle.join().ok();

    assert_eq!(bytes, payload, "payload must be fully reconstructed");
    assert_eq!(
        parsed_total,
        Some(total as u64),
        "total must be learned from the server headers"
    );
    assert_eq!(seen_total, Some(total as u64));
    assert!(
        progress_points.windows(2).all(|w| w[1] >= w[0]),
        "progress must never go backwards across reconnects: {:?}",
        progress_points
    );
    assert_eq!(
        *progress_points.last().expect("at least one progress point"),
        total as u64,
        "final progress must reach the full size"
    );
}
